name: New Label Config Request
description: Request the creation of a new label configuration
title: "[NEW CONFIG] "
labels: ["new-config"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting a new label configuration for the Awesome Label Studio Config community!
        
  - type: input
    id: config-name
    attributes:
      label: Proposed Config Name
      description: What would you like to call this configuration?
      placeholder: e.g., audio-classification-with-regions
    validations:
      required: true
      
  - type: textarea
    id: config-description
    attributes:
      label: Configuration Description
      description: Describe what this label configuration should do
      placeholder: A label configuration for annotating audio files with classifications and region-based comments...
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What labeling task or scenario is this config for?
      placeholder: This config would be used for labeling audio files where users need to...
    validations:
      required: true
      
  - type: textarea
    id: data-format
    attributes:
      label: Data Format
      description: What format is your input data in? Provide a sample if possible.
      placeholder: |
        ```json
        {
          "audio": "https://example.com/sample.mp3",
          "metadata": {
            "duration": 120
          }
        }
        ```
    validations:
      required: false
      
  - type: textarea
    id: special-requirements
    attributes:
      label: Special Requirements
      description: Any specific tags, controls, or features needed?
      placeholder: The config should include audio player controls, classification labels, and the ability to mark regions...
    validations:
      required: false
      
  - type: textarea
    id: examples
    attributes:
      label: Similar Examples
      description: Any similar existing configs or examples you can reference?
      placeholder: The html-ner-tagging config is similar, but I need audio support instead...
    validations:
      required: false
      
  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute this config yourself?
      options:
        - Yes, I'd like to implement this
        - I need help implementing this
        - I'm just suggesting the idea
    validations:
      required: true